Update deploy.yaml

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -1,5 +1,4 @@
 name: CI/CD auth-app
-
 on:
   push:
     branches:
@@ -9,20 +8,17 @@ jobs:
   deploy_main:
     runs-on: self-hosted
     steps:
-      - name: Debug Password (Optional)
-        run: echo "Password length: ${#secrets.PASSWORD}" # Check if the password is retrieved correctly
-
       - name: Run execute.sh in frontend directory as root
         run: |
-          printf '%s\n' "${{ secrets.PASSWORD }}" | sudo -S su -c '
+          printf '%s\n' "${{ secrets.PASSWORD }}" | sudo -S su -c "
             cd /home/ubuntu/class-connect/frontend &&
             chmod +x ./execute.sh &&
-            ./execute.sh || echo "Failed to execute frontend script"
-          '
+            ./execute.sh || echo 'Failed to execute frontend script'
+          "
 
       - name: Run Docker Compose in backend directory as root
         run: |
-          printf '%s\n' "${{ secrets.PASSWORD }}" | sudo -S su -c '
+          printf '%s\n' "${{ secrets.PASSWORD }}" | sudo -S su -c "
             cd /home/ubuntu/class-connect/backend/monolythic &&
-            docker compose -f prod.yml up -d || echo "Failed to start Docker containers"
-          '
+            docker compose -f prod.yml up -d || echo 'Failed to start Docker containers'
+          "
